swagger: '2.0'
info:
  description: 'Documentation for ISO Catalog Finder'
  version: '0.0.0 (BETA)'
  title: 'ISO Catalog Finder Documentation'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: 'apiteam@swagger.io'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'http://catalog-finder.herokuapp.com/'
basePath: '/api/'
schemes:
  - 'http'
  - 'https'

paths:
  /admin/events/{eventId}/files:
    delete:
      tags:
        - 'Events'
      summary: 'Return status of deleted event files image by id'
      description: 'For the files which are not presented in public folder, it will return unknown'
      produces:
        - 'application/json'
      parameters:
        - name: 'eventId'
          in: 'path'
          description: 'ID of event whose file you want to delete'
          required: true
          type: 'integer'
          format: 'int64'
      security:
        - api_key: []
      responses:
        '200':
          description: 'Success delete file'
          schema:
            $ref: '#/definitions/DeleteResponse'

definitions:
  # The schema of Event
  DeleteResponse:
    type: 'object'
    required:
      - 'name'
      - 'description'
      - 'originalFee'
      - 'actualFee'
      - 'startedAt'
      - 'endedAt'
      - 'vendor'
    properties:
      name:
        type: 'string'
        description: 'The name of event'
      description:
        type: 'string'
        description: 'The description of event'
      originalFee:
        type: 'number'
        description: 'The original fee of event'
      actualFee:
        type: 'number'
        description: 'The fee of event after discount'
      startedAt:
        type: 'string'
        description: 'The start date of event on local time'
      endedAt:
        type: 'string'
        description: 'The end date of event on local time'
      vendor:
        type: 'string'
        description: 'The name of event organizer'
      slug:
        type: 'string'
        description: 'The name of event with url safety'
      publicId:
        type: 'string'
        description: 'The event Id for public'
      wowzaLivestreamID:
        type: 'string'
        description: 'LivestreamId inside Wowza Streaming Cloud'
      wowzaLivestreamSecret:
        type: 'string'
        description: 'Secret key is Shared Secret for generating Token Authentication'
      wowzaLivestreamURL:
        type: 'string'
        description: 'HLS Playback URL for livestreaming from Wowza'
      wowzaLivestreamState:
        type: 'string'
        enum:
          - starting
          - stopping
          - started
          - stopped
          - resetting
        description: The state of the live stream.
      wowzaFastlyId:
        type: 'string'
        description: 'The Fastly stream ID from the stream target playback_url,
          used for generating Token Authentication'
      wowzaAspectRatioWidth:
        default: '1920'
        type: 'integer'
        description: 'Width aspect ratio for the video source.'
      wowzaAspectRatioHeight:
        default: '1080'
        type: 'integer'
        description: 'Heigth aspect ratio for the video source.'
      wowzaLivestreamServerUrl:
        type: 'string'
        description: 'Primary server to connect source to Wowza Streaming Cloud.
          The url is in rtmp protocol'
      wowzaLivestreamServerPort:
        type: 'string'
        description: 'A port for configure your source to connect to Wowza Streaming Cloud'
      wowzaLivestreamStreamName:
        type: 'string'
        description: 'A stream name for connecting to Wowza Streaming Cloud'
      wowzaSourceUsername:
        type: 'string'
        description: 'Username for configure authentication in source video'
      wowzaSourcePassword:
        type: 'string'
        description: 'Password for configure authentication in source video'
      wowzaPlayerUrl:
        type: 'string'
        description: 'Player URL that hosted by Wowza Streaming Cloud'
      urlAccess:
        type: 'string'
        description: 'Youtube Playback URL for alternative playback'
